#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""RtrayModel.py: View part of rtray generated by wxGlade."""
# generated by wxGlade 0.6.3 on Thu Nov 24 15:18:56 2011

import wx

# begin wxGlade: extracode
# end wxGlade

__author__ = "Yann Melikoff"
__copyright__ = "Copyright 2011"
__credits__ = ["Yann Melikoff"]
__license__ = "GPL"
__version__ = "0.1"
__email__ = "yann punto cappa emme emme chiocciola gmail punto com"
__status__ = "Development"

class AuthFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AuthFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FRAME_NO_TASKBAR|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_url = wx.StaticText(self, -1, u"sadqasdaij asdòlajiods alòdj aòdakljd aòlkja òlkajs d")
        self.label_user = wx.StaticText(self.panel_1, -1, "Username")
        self.text_ctrl_user = wx.TextCtrl(self.panel_1, -1, "")
        self.label_pass = wx.StaticText(self.panel_1, -1, "Password")
        self.text_ctrl_pass = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_PASSWORD)
        self.button_login = wx.Button(self, -1, "Login")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AuthFrame.__set_properties
        self.SetTitle("RT Auth")
        self.button_login.SetMinSize((85, 29))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AuthFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(self.label_url, 0, 0, 0)
        grid_sizer_2.Add(self.label_user, 0, 0, 0)
        grid_sizer_2.Add(self.text_ctrl_user, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_pass, 0, 0, 0)
        grid_sizer_2.Add(self.text_ctrl_pass, 0, wx.EXPAND, 0)
        self.panel_1.SetSizer(grid_sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_1.Add(self.button_login, 0, wx.ALIGN_RIGHT, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class AuthFrame


class RttrayFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RttrayFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FRAME_NO_TASKBAR|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RttrayFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RttrayFrame.__do_layout
        self.Layout()
        # end wxGlade

# end of class RttrayFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = RttrayFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
